import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Nabvar from "@/components/Navbar";
import HomeFirst from "@/components/HomeFirst";
import Header from "@/components/Header";

const inter = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>
        <Header />
        <Nabvar />
        <div className="bg-image mb-10">
          <HomeFirst />
        </div>
        {children}
      </body>
    </html>
  );
}
